#!/usr/bin/env python3
"""Failure-preserving build runner for the confirmatory dynamical representation.

The runner accepts only the committed confirmatory-v1 design.  It derives
exactly one Van der Pol representation by reusing the previously verified
frozen KAHM abstraction, changing only the prespecified association omega,
and refitting the NLMS operator from the original training trajectories.

No confirmatory certificate-evaluation pairs are generated by this runner.

Production requirements:
- clean committed source tree;
- source files byte-identical to HEAD;
- output directory outside the source working tree and initially absent;
- retained configuration/protocol bytes;
- retained environment and test preflight logs;
- failure-preserving metadata;
- complete SHA256SUMS inventory.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict
from datetime import datetime, timezone
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
import time
import traceback
from typing import Any

from kahkm_confirmatory_representation import (
    CONFIRMATORY_CONFIG_RELATIVE,
    CONFIRMATORY_CONFIG_SHA256,
    CONFIRMATORY_PROTOCOL_RELATIVE,
    CONFIRMATORY_PROTOCOL_SHA256,
    DERIVATION_ID,
    derive_confirmatory_representation,
)


ROOT = Path(
    __file__
).resolve().parent

RUNNER_ID = (
    "confirmatory_dynamical_representation_build_v1"
)

REQUIRED_SOURCE_FILES = (
    "build_confirmatory_dynamical_representation.py",
    "kahkm_confirmatory_representation.py",
    "test_build_confirmatory_dynamical_representation.py",
    "test_kahkm_confirmatory_representation.py",
    "kahkm_dynamical_frozen_source.py",
    "kahkm_frozen_representation.py",
    "kernel_affine_hull_koopman_machines.py",
    "experiment_15_external_koopman_baselines.py",
    CONFIRMATORY_CONFIG_RELATIVE,
    CONFIRMATORY_PROTOCOL_RELATIVE,
    "requirements-lock-arm64.txt",
    "scripts/verify_environment.py",
    (
        "reproduction/prospective_campaigns/"
        "dynamical_frozen_representations_pilot_v1_run001/"
        "ARCHIVE.json"
    ),
    (
        "reproduction/prospective_campaigns/"
        "dynamical_frozen_representations_pilot_v1_run001/"
        "README.md"
    ),
    (
        "reproduction/prospective_campaigns/"
        "dynamical_frozen_representations_pilot_v1_run001/"
        "SHA256SUMS"
    ),
    (
        "reproduction/prospective_campaigns/"
        "dynamical_frozen_representations_pilot_v1_run001/"
        "evidence.tar.gz"
    ),
)


def utc_now() -> str:
    return datetime.now(
        timezone.utc
    ).isoformat()


def file_sha256(
    path: str | os.PathLike[str],
) -> str:
    digest = hashlib.sha256()

    with Path(path).open(
        "rb"
    ) as handle:
        for block in iter(
            lambda: handle.read(
                1024
                * 1024
            ),
            b"",
        ):
            digest.update(
                block
            )

    return digest.hexdigest()


def git_bytes(
    *args: str,
) -> bytes:
    return subprocess.check_output(
        [
            "git",
            *args,
        ],
        cwd=ROOT,
        stdin=subprocess.DEVNULL,
    )


def strict_json_dump(
    path: Path,
    value: Any,
) -> None:
    serialized = (
        json.dumps(
            value,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n"
    ).encode(
        "utf-8"
    )

    with path.open(
        "xb"
    ) as handle:
        handle.write(
            serialized
        )
        handle.flush()
        os.fsync(
            handle.fileno()
        )


def write_bytes_exact(
    path: Path,
    raw: bytes,
) -> None:
    with path.open(
        "xb"
    ) as handle:
        handle.write(
            raw
        )
        handle.flush()
        os.fsync(
            handle.fileno()
        )


def source_snapshot() -> dict[str, Any]:
    """Require a clean committed source and hash every required file."""

    actual_root = Path(
        git_bytes(
            "rev-parse",
            "--show-toplevel",
        )
        .decode()
        .strip()
    ).resolve()

    if actual_root != ROOT:
        raise RuntimeError(
            "Representation runner must execute from its repository root."
        )

    commit = (
        git_bytes(
            "rev-parse",
            "HEAD",
        )
        .decode()
        .strip()
    )

    status = (
        git_bytes(
            "status",
            "--porcelain=v1",
            "--untracked-files=all",
        )
        .decode()
    )

    if status:
        raise RuntimeError(
            "A clean source working tree is required:\n"
            + status
        )

    hashes: dict[
        str,
        str,
    ] = {}

    for relative_name in sorted(
        set(
            REQUIRED_SOURCE_FILES
        )
    ):
        path = (
            ROOT
            / relative_name
        )

        if (
            path.is_symlink()
            or not path.is_file()
        ):
            raise RuntimeError(
                "Missing or symlinked build source file: "
                f"{relative_name}"
            )

        actual = file_sha256(
            path
        )

        try:
            committed_bytes = git_bytes(
                "show",
                f"{commit}:{relative_name}",
            )

        except subprocess.CalledProcessError as exc:
            raise RuntimeError(
                "Build source file is not committed at HEAD: "
                f"{relative_name}"
            ) from exc

        committed = hashlib.sha256(
            committed_bytes
        ).hexdigest()

        if actual != committed:
            raise RuntimeError(
                "Build source bytes differ from HEAD: "
                f"{relative_name}"
            )

        hashes[
            relative_name
        ] = actual

    return {
        "execution_source_commit":
            commit,

        "git_status_porcelain":
            status,

        "source_file_sha256":
            hashes,
    }


def load_configuration() -> tuple[
    bytes,
    dict[str, Any],
]:
    path = (
        ROOT
        / CONFIRMATORY_CONFIG_RELATIVE
    )

    raw = path.read_bytes()

    actual = hashlib.sha256(
        raw
    ).hexdigest()

    if (
        actual
        != CONFIRMATORY_CONFIG_SHA256
    ):
        raise ValueError(
            "Confirmatory configuration bytes differ from "
            "the supported frozen design."
        )

    payload = json.loads(
        raw
    )

    if not isinstance(
        payload,
        dict,
    ):
        raise TypeError(
            "Confirmatory configuration must contain a JSON object."
        )

    if (
        payload.get(
            "campaign_id"
        )
        != "dynamical_original_iid_confirmatory_v1"
    ):
        raise ValueError(
            "Unexpected confirmatory campaign identifier."
        )

    if (
        payload.get(
            "campaign_role"
        )
        != "confirmatory"
    ):
        raise ValueError(
            "Expected campaign_role='confirmatory'."
        )

    design = payload.get(
        "confirmatory_design"
    )

    if not isinstance(
        design,
        dict,
    ):
        raise TypeError(
            "confirmatory_design must be an object."
        )

    if design.get(
        "systems"
    ) != [
        "vanderpol"
    ]:
        raise ValueError(
            "Confirmatory representation build must contain only Van der Pol."
        )

    if design.get(
        "sample_sizes"
    ) != [
        16384
    ]:
        raise ValueError(
            "Unexpected confirmatory sample-size design."
        )

    if int(
        design.get(
            "replicates_per_cell",
            -1,
        )
    ) != 32:
        raise ValueError(
            "Unexpected confirmatory replicate design."
        )

    return (
        raw,
        payload,
    )


def load_protocol() -> bytes:
    path = (
        ROOT
        / CONFIRMATORY_PROTOCOL_RELATIVE
    )

    raw = path.read_bytes()

    actual = hashlib.sha256(
        raw
    ).hexdigest()

    if (
        actual
        != CONFIRMATORY_PROTOCOL_SHA256
    ):
        raise ValueError(
            "Confirmatory protocol bytes differ from the frozen design."
        )

    return raw


def run_preflight(
    output: Path,
) -> None:
    """Retain environment/test logs before any representation derivation."""

    checks = (
        (
            "environment",
            [
                sys.executable,
                "scripts/verify_environment.py",
            ],
        ),
        (
            "pip_check",
            [
                sys.executable,
                "-m",
                "pip",
                "check",
            ],
        ),
        (
            "confirmatory_unit_tests",
            [
                sys.executable,
                "-m",
                "unittest",
                "-v",
                "test_kahkm_confirmatory_representation",
                "test_build_confirmatory_dynamical_representation",
            ],
        ),
        (
            "certificate_test_suite",
            [
                sys.executable,
                "-m",
                "unittest",
                "discover",
                "-s",
                "tests",
                "-p",
                "test_kahkm_*.py",
                "-v",
            ],
        ),
        (
            "pip_freeze",
            [
                sys.executable,
                "-m",
                "pip",
                "freeze",
                "--all",
            ],
        ),
    )

    logs = (
        output
        / "checks"
    )

    logs.mkdir(
        exist_ok=False
    )

    for name, command in checks:
        strict_json_dump(
            logs
            / f"{name}.command.json",
            {
                "command":
                    command,

                "cwd":
                    str(
                        ROOT
                    ),
            },
        )

        with (
            (
                logs
                / f"{name}.stdout.log"
            ).open(
                "xb"
            ) as stdout,
            (
                logs
                / f"{name}.stderr.log"
            ).open(
                "xb"
            ) as stderr,
        ):
            completed = subprocess.run(
                command,
                cwd=ROOT,
                stdin=subprocess.DEVNULL,
                stdout=stdout,
                stderr=stderr,
                check=False,
            )

        strict_json_dump(
            logs
            / f"{name}.result.json",
            {
                "returncode":
                    completed.returncode,
            },
        )

        if (
            completed.returncode
            != 0
        ):
            raise RuntimeError(
                f"Preflight {name} failed; see retained check logs."
            )

    packages = []

    for line in (
        ROOT
        / "requirements-lock-arm64.txt"
    ).read_text(
        encoding="utf-8"
    ).splitlines():
        stripped = line.strip()

        if (
            not stripped
            or stripped.startswith(
                "#"
            )
        ):
            continue

        name, separator, expected = (
            stripped.partition(
                "=="
            )
        )

        if (
            not separator
            or not expected
        ):
            raise ValueError(
                "Unsupported lockfile entry: "
                + stripped
            )

        actual = (
            importlib.metadata.version(
                name
            )
        )

        packages.append(
            {
                "name":
                    name,

                "expected":
                    expected,

                "actual":
                    actual,

                "matches":
                    (
                        actual
                        == expected
                    ),
            }
        )

    strict_json_dump(
        logs
        / "locked_packages.json",
        packages,
    )

    if not all(
        item[
            "matches"
        ]
        for item in packages
    ):
        raise RuntimeError(
            "Installed packages differ from the reference lockfile."
        )


def write_checksums(
    output: Path,
) -> None:
    files = sorted(
        path
        for path in output.rglob(
            "*"
        )
        if path.is_file()
        and path.name
        != "SHA256SUMS"
    )

    with (
        output
        / "SHA256SUMS"
    ).open(
        "x",
        encoding="utf-8",
        newline="\n",
    ) as handle:
        for path in files:
            handle.write(
                f"{file_sha256(path)}  "
                f"{path.relative_to(output).as_posix()}\n"
            )

        handle.flush()
        os.fsync(
            handle.fileno()
        )


def run_build(
    output_dir: str | os.PathLike[str],
) -> int:
    output = Path(
        output_dir
    ).expanduser().resolve()

    if (
        output
        == ROOT
        or ROOT
        in output.parents
    ):
        raise ValueError(
            "Choose a new output directory outside this working tree."
        )

    if output.exists():
        raise FileExistsError(
            "Output already exists; it will not be reused or overwritten."
        )

    config_raw, config = (
        load_configuration()
    )

    protocol_raw = (
        load_protocol()
    )

    source_before = (
        source_snapshot()
    )

    work = (
        output.parent
        / (
            f".{output.name}."
            "vanderpol."
            "representation-work"
        )
    )

    if work.exists():
        raise FileExistsError(
            f"Representation work directory already exists: {work}"
        )

    output.mkdir(
        parents=True,
        exist_ok=False,
    )

    started = utc_now()
    monotonic_start = (
        time.monotonic()
    )

    summary: dict[
        str,
        Any,
    ] = {
        "runner_id":
            RUNNER_ID,

        "campaign_id":
            config[
                "campaign_id"
            ],

        "campaign_role":
            config[
                "campaign_role"
            ],

        "status":
            "initializing",

        "started_utc":
            started,

        "execution_source_commit":
            source_before[
                "execution_source_commit"
            ],

        "configuration_sha256":
            CONFIRMATORY_CONFIG_SHA256,

        "protocol_sha256":
            CONFIRMATORY_PROTOCOL_SHA256,

        "representation_derivation_id":
            DERIVATION_ID,

        "planned_systems": [
            "vanderpol"
        ],

        "num_systems_planned":
            1,

        "num_systems_built":
            0,

        "systems_built":
            [],

        "build_records":
            [],

        "state_space_kmeans_refits":
            0,

        "autoencoder_refits":
            0,

        "nlms_operator_refits":
            0,

        "random_evaluation_pairs_generated":
            0,

        "certificate_evaluation_pairs_generated":
            0,

        "source_unchanged":
            False,

        "independent_evidence_verification":
            "not_yet_performed",
    }

    exit_code = 1

    try:
        write_bytes_exact(
            output
            / "configuration.json",
            config_raw,
        )

        write_bytes_exact(
            output
            / "protocol.md",
            protocol_raw,
        )

        strict_json_dump(
            output
            / "source_before.json",
            source_before,
        )

        strict_json_dump(
            output
            / "build_metadata.json",
            {
                "runner_id":
                    RUNNER_ID,

                "campaign_id":
                    config[
                        "campaign_id"
                    ],

                "campaign_role":
                    config[
                        "campaign_role"
                    ],

                "output_path":
                    str(
                        output
                    ),

                "repository_path":
                    str(
                        ROOT
                    ),

                "configuration_path":
                    CONFIRMATORY_CONFIG_RELATIVE,

                "configuration_sha256":
                    CONFIRMATORY_CONFIG_SHA256,

                "protocol_path":
                    CONFIRMATORY_PROTOCOL_RELATIVE,

                "protocol_sha256":
                    CONFIRMATORY_PROTOCOL_SHA256,

                "derivation_id":
                    DERIVATION_ID,

                "source":
                    source_before,

                "python_executable":
                    sys.executable,

                "python_version":
                    sys.version,

                "platform":
                    platform.platform(),

                "architecture":
                    platform.machine(),

                "argv":
                    sys.argv,

                "process_id":
                    os.getpid(),

                "started_utc":
                    started,

                "numerical_environment": {
                    name:
                        os.environ.get(
                            name
                        )
                    for name in (
                        "OMP_NUM_THREADS",
                        "OPENBLAS_NUM_THREADS",
                        "MKL_NUM_THREADS",
                        "VECLIB_MAXIMUM_THREADS",
                        "NUMEXPR_NUM_THREADS",
                        "PYTHONHASHSEED",
                    )
                },
            },
        )

        summary[
            "status"
        ] = "preflight"

        run_preflight(
            output
        )

        source_after_preflight = (
            source_snapshot()
        )

        if (
            source_after_preflight
            != source_before
        ):
            raise RuntimeError(
                "Source changed during preflight; representation build "
                "not started."
            )

        summary[
            "status"
        ] = "building"

        representation_dir = (
            output
            / "representations"
            / "vanderpol"
        )

        representation_dir.parent.mkdir(
            parents=True,
            exist_ok=False,
        )

        result = (
            derive_confirmatory_representation(
                repository_root=
                    ROOT,

                output_dir=
                    representation_dir,

                work_dir=
                    work,
            )
        )

        if work.exists():
            raise RuntimeError(
                "Representation derivation left a work directory behind."
            )

        source_after_build = (
            source_snapshot()
        )

        if (
            source_after_build
            != source_before
        ):
            raise RuntimeError(
                "Source changed during representation build."
            )

        summary[
            "num_systems_built"
        ] = 1

        summary[
            "systems_built"
        ] = [
            "vanderpol"
        ]

        summary[
            "build_records"
        ] = [
            asdict(
                result
            )
        ]

        summary[
            "nlms_operator_refits"
        ] = 1

        summary[
            "source_unchanged"
        ] = True

        summary[
            "status"
        ] = "completed"

        summary[
            "ended_utc"
        ] = utc_now()

        summary[
            "elapsed_seconds"
        ] = (
            time.monotonic()
            - monotonic_start
        )

        summary[
            "exit_code"
        ] = 0

        strict_json_dump(
            output
            / "source_after.json",
            source_after_build,
        )

        strict_json_dump(
            output
            / "build_summary.json",
            summary,
        )

        write_checksums(
            output
        )

        exit_code = 0

    except BaseException as exc:
        summary[
            "aborted_stage"
        ] = summary[
            "status"
        ]

        summary[
            "status"
        ] = "aborted"

        summary[
            "ended_utc"
        ] = utc_now()

        summary[
            "elapsed_seconds"
        ] = (
            time.monotonic()
            - monotonic_start
        )

        summary[
            "exit_code"
        ] = 1

        summary[
            "error_type"
        ] = type(
            exc
        ).__name__

        summary[
            "error"
        ] = str(
            exc
        )

        summary[
            "traceback"
        ] = traceback.format_exc()

        try:
            current_source = (
                source_snapshot()
            )

            summary[
                "source_unchanged"
            ] = (
                current_source
                == source_before
            )

            source_after_path = (
                output
                / "source_after.json"
            )

            if not source_after_path.exists():
                strict_json_dump(
                    source_after_path,
                    current_source,
                )

        except BaseException as source_exc:
            summary[
                "source_inspection_error"
            ] = str(
                source_exc
            )

        summary_path = (
            output
            / "build_summary.json"
        )

        if not summary_path.exists():
            try:
                strict_json_dump(
                    summary_path,
                    summary,
                )

            except BaseException:
                pass

        failure_path = (
            output
            / "failure.json"
        )

        if not failure_path.exists():
            try:
                strict_json_dump(
                    failure_path,
                    {
                        "runner_id":
                            RUNNER_ID,

                        "campaign_id":
                            config[
                                "campaign_id"
                            ],

                        "execution_source_commit":
                            source_before[
                                "execution_source_commit"
                            ],

                        "configuration_sha256":
                            CONFIRMATORY_CONFIG_SHA256,

                        "protocol_sha256":
                            CONFIRMATORY_PROTOCOL_SHA256,

                        "aborted_stage":
                            summary[
                                "aborted_stage"
                            ],

                        "error_type":
                            type(
                                exc
                            ).__name__,

                        "error":
                            str(
                                exc
                            ),

                        "traceback":
                            traceback.format_exc(),
                    },
                )

            except BaseException:
                pass

        checksums = (
            output
            / "SHA256SUMS"
        )

        if not checksums.exists():
            try:
                write_checksums(
                    output
                )

            except BaseException:
                pass

        print(
            "Confirmatory representation build FAILED:",
            f"{type(exc).__name__}: {exc}",
            file=sys.stderr,
        )

        return 1

    print(
        json.dumps(
            summary,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
    )

    return exit_code


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__
    )

    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help=(
            "New evidence directory outside the source working tree."
        ),
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        return run_build(
            args.output
        )

    except BaseException as exc:
        print(
            "STOP:",
            f"{type(exc).__name__}: {exc}",
            file=sys.stderr,
        )

        print(
            "Retain any created output directory; do not overwrite it.",
            file=sys.stderr,
        )

        return 2


if __name__ == "__main__":
    raise SystemExit(
        main()
    )
