#!/usr/bin/env python3
"""Generate manuscript Table 5: projection diagnostics.

This wrapper is intended to be placed in the same folder as the experiment
scripts from the manuscript archive. It runs, or reuses, the two projection
experiments and formats the table values used in the manuscript:

  - Duffing:      experiment_04_duffing_projection_diagnostics.py
  - Van der Pol:  experiment_08_vanderpol_projection_diagnostics.py

Important manuscript convention
-------------------------------
The Van der Pol projection table is a diagnostic default-setting table and must
use C=20, omega=4. The underlying experiment_08 script has older local defaults
(C=15, omega=12), so this wrapper explicitly passes --n-clusters 20 --omega 4.

Outputs
-------
By default, writes:

  kahkm_table5_projection/table5_projection_values.csv
  kahkm_table5_projection/table5_projection_values.md
  kahkm_table5_projection/table5_projection_values.tex
  kahkm_table5_projection/table5_projection_metadata.json

Usage
-----
From the folder containing the experiment scripts:

  python step_04_generate_table5_projection.py

Reuse existing outputs generated by this wrapper:

  python step_04_generate_table5_projection.py --no-run

Reuse explicit summaries:

  python step_04_generate_table5_projection.py --no-run \
    --duffing-summary kahkm_table5_projection/exp04_duffing_projection/experiment_04_projection_summary.csv \
    --vanderpol-summary kahkm_table5_projection/exp08_vanderpol_projection/experiment_08_projection_summary.csv
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Mapping, Sequence, TypeAlias, cast

CsvRow: TypeAlias = dict[str, str]

HORIZONS: tuple[int, int, int] = (1, 20, 200)

MODE_TO_LABEL: dict[str, str] = {
    "raw_free": r"raw $\widehat{B}$",
    "raw_simplex_project_each_step": r"raw $\widehat{B}$ + simplex projection",
    "row_stochastic_free": "row-stochastic matrix",
}

DISPLAY_MODE_ORDER: tuple[str, str, str] = (
    "raw_free",
    "raw_simplex_project_each_step",
    "row_stochastic_free",
)


@dataclass(frozen=True)
class CliArgs:
    source_dir: Path
    output_dir: Path
    no_run: bool
    duffing_summary: Path | None
    vanderpol_summary: Path | None
    python_executable: str
    force: bool


@dataclass(frozen=True)
class Metric:
    mean: float
    std: float


@dataclass(frozen=True)
class TableRow:
    system: str
    rollout_mode_key: str
    rollout_mode_label: str
    e1: Metric
    e20: Metric
    e200: Metric

    def to_csv_row(self) -> CsvRow:
        return {
            "system": self.system,
            "rollout_mode": self.rollout_mode_key,
            "rollout_mode_label": self.rollout_mode_label.replace("$", ""),
            "E1_mean": _float_to_csv(self.e1.mean),
            "E1_std": _float_to_csv(self.e1.std),
            "E20_mean": _float_to_csv(self.e20.mean),
            "E20_std": _float_to_csv(self.e20.std),
            "E200_mean": _float_to_csv(self.e200.mean),
            "E200_std": _float_to_csv(self.e200.std),
            "E1_table_cell": _format_sci(self.e1.mean, digits=3),
            "E20_table_cell": _format_sci(self.e20.mean, digits=3),
            "E200_table_cell": _format_sci(self.e200.mean, digits=3),
        }


def _parse_args() -> CliArgs:
    parser = argparse.ArgumentParser(description="Generate manuscript Table 5 projection diagnostics.")
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Folder containing the manuscript experiment scripts. Default: folder containing this wrapper.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("kahkm_table5_projection"),
        help="Output folder for wrapper results and, by default, experiment outputs.",
    )
    parser.add_argument(
        "--no-run",
        action="store_true",
        help="Do not execute experiments; only read existing summary CSV files.",
    )
    parser.add_argument(
        "--duffing-summary",
        type=Path,
        default=None,
        help="Optional explicit path to experiment_04_projection_summary.csv.",
    )
    parser.add_argument(
        "--vanderpol-summary",
        type=Path,
        default=None,
        help="Optional explicit path to experiment_08_projection_summary.csv.",
    )
    parser.add_argument(
        "--python-executable",
        type=str,
        default=sys.executable,
        help="Python executable used to run the underlying experiment scripts.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-run experiments even when the expected wrapper summary CSVs already exist.",
    )
    namespace = parser.parse_args()
    return CliArgs(
        source_dir=Path(cast(Path, namespace.source_dir)).resolve(),
        output_dir=Path(cast(Path, namespace.output_dir)),
        no_run=bool(namespace.no_run),
        duffing_summary=None if namespace.duffing_summary is None else Path(cast(Path, namespace.duffing_summary)),
        vanderpol_summary=None if namespace.vanderpol_summary is None else Path(cast(Path, namespace.vanderpol_summary)),
        python_executable=str(namespace.python_executable),
        force=bool(namespace.force),
    )


def _float_to_csv(value: float) -> str:
    if math.isnan(value):
        return "nan"
    if math.isinf(value):
        return "inf" if value > 0.0 else "-inf"
    return f"{value:.17g}"


def _format_sci(value: float, *, digits: int = 3) -> str:
    """Format a positive float as manuscript-style LaTeX scientific notation."""
    if not math.isfinite(value):
        return str(value)
    if value == 0.0:
        return "0"
    exponent = int(math.floor(math.log10(abs(value))))
    coefficient = value / (10.0 ** exponent)
    coefficient_text = f"{coefficient:.{digits - 1}f}".rstrip("0").rstrip(".")
    return rf"${coefficient_text}\times10^{{{exponent}}}$"


def _require_file(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Missing {label}: {path}")
    if not path.is_file():
        raise FileNotFoundError(f"Expected {label} to be a file, got: {path}")


def _run_command(command: Sequence[str], *, cwd: Path) -> None:
    printable = " ".join(command)
    print(f"\n$ {printable}")
    completed = subprocess.run(command, cwd=cwd, check=False)
    if completed.returncode != 0:
        raise RuntimeError(f"Command failed with exit code {completed.returncode}: {printable}")


def _expected_paths(args: CliArgs) -> tuple[Path, Path, Path, Path]:
    root = args.output_dir
    duffing_dir = root / "exp04_duffing_projection"
    vanderpol_dir = root / "exp08_vanderpol_projection"
    duffing_summary = duffing_dir / "experiment_04_projection_summary.csv"
    vanderpol_summary = vanderpol_dir / "experiment_08_projection_summary.csv"
    return duffing_dir, vanderpol_dir, duffing_summary, vanderpol_summary


def _run_experiments(args: CliArgs) -> tuple[Path, Path]:
    exp04_script = args.source_dir / "experiment_04_duffing_projection_diagnostics.py"
    exp08_script = args.source_dir / "experiment_08_vanderpol_projection_diagnostics.py"
    _require_file(exp04_script, "Duffing projection experiment script")
    _require_file(exp08_script, "Van der Pol projection experiment script")

    duffing_dir, vanderpol_dir, duffing_summary, vanderpol_summary = _expected_paths(args)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    if args.force or not duffing_summary.exists():
        _run_command(
            [
                args.python_executable,
                str(exp04_script),
                "--output-dir",
                str(duffing_dir),
            ],
            cwd=args.source_dir,
        )
    else:
        print(f"Reusing Duffing summary: {duffing_summary}")

    if args.force or not vanderpol_summary.exists():
        _run_command(
            [
                args.python_executable,
                str(exp08_script),
                "--output-dir",
                str(vanderpol_dir),
                "--n-clusters",
                "20",
                "--omega",
                "4",
            ],
            cwd=args.source_dir,
        )
    else:
        print(f"Reusing Van der Pol summary: {vanderpol_summary}")

    return duffing_summary, vanderpol_summary


def _resolve_summaries(args: CliArgs) -> tuple[Path, Path]:
    _, _, default_duffing_summary, default_vanderpol_summary = _expected_paths(args)

    if args.no_run:
        duffing_summary = args.duffing_summary or _first_existing(
            [
                default_duffing_summary,
                args.source_dir / "kahkm_experiment_04_outputs" / "experiment_04_projection_summary.csv",
            ]
        )
        vanderpol_summary = args.vanderpol_summary or _first_existing(
            [
                default_vanderpol_summary,
                args.source_dir / "kahkm_experiment_08_outputs" / "experiment_08_projection_summary.csv",
            ]
        )
    else:
        duffing_summary, vanderpol_summary = _run_experiments(args)

    _require_file(duffing_summary, "Duffing projection summary")
    _require_file(vanderpol_summary, "Van der Pol projection summary")
    return duffing_summary, vanderpol_summary


def _first_existing(paths: Sequence[Path]) -> Path:
    for path in paths:
        if path.exists():
            return path
    return paths[0]


def _read_summary(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = [dict(row) for row in reader]
    if not rows:
        raise ValueError(f"No rows found in {path}")
    required = {
        "rollout_mode",
        "horizon",
        "relative_association_error_mean",
        "relative_association_error_std",
    }
    missing = sorted(required.difference(rows[0].keys()))
    if missing:
        raise ValueError(f"Summary file {path} is missing required columns: {missing}")
    return rows


def _metric_for(rows: Sequence[Mapping[str, str]], *, mode: str, horizon: int, source_path: Path) -> Metric:
    matches = [
        row
        for row in rows
        if str(row.get("rollout_mode", "")) == mode and int(float(str(row.get("horizon", "nan")))) == horizon
    ]
    if len(matches) != 1:
        raise ValueError(f"Expected exactly one row for mode={mode!r}, horizon={horizon} in {source_path}; found {len(matches)}")
    row = matches[0]
    return Metric(
        mean=float(str(row["relative_association_error_mean"])),
        std=float(str(row["relative_association_error_std"])),
    )


def _build_system_rows(system: str, rows: Sequence[Mapping[str, str]], *, source_path: Path) -> list[TableRow]:
    table_rows: list[TableRow] = []
    for mode in DISPLAY_MODE_ORDER:
        metrics = {
            horizon: _metric_for(rows, mode=mode, horizon=horizon, source_path=source_path)
            for horizon in HORIZONS
        }
        table_rows.append(
            TableRow(
                system=system,
                rollout_mode_key=mode,
                rollout_mode_label=MODE_TO_LABEL[mode],
                e1=metrics[1],
                e20=metrics[20],
                e200=metrics[200],
            )
        )
    return table_rows


def _write_csv(path: Path, rows: Sequence[TableRow]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    csv_rows = [row.to_csv_row() for row in rows]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(csv_rows[0].keys()))
        writer.writeheader()
        writer.writerows(csv_rows)


def _write_markdown(path: Path, rows: Sequence[TableRow]) -> None:
    lines = [
        "# Table 5: Projection diagnostics",
        "",
        "Errors are mean relative association errors over three runs. Standard deviations are retained in the CSV for auditing, but the manuscript table reports means only.",
        "",
        "| System | Rollout mode | E1 | E20 | E200 |",
        "|---|---|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    row.system,
                    row.rollout_mode_label.replace("$", ""),
                    _format_sci(row.e1.mean, digits=3).replace("$", ""),
                    _format_sci(row.e20.mean, digits=3).replace("$", ""),
                    _format_sci(row.e200.mean, digits=3).replace("$", ""),
                ]
            )
            + " |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_latex(path: Path, rows: Sequence[TableRow]) -> None:
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Projection diagnostics. Errors are mean relative association errors over three runs. The row-stochastic matrix is useful for interpretation, but is not the best predictive operator in these experiments.}",
        r"\label{tab:projection}",
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"System & Rollout mode & $E_1$ & $E_{20}$ & $E_{200}$ \\",
        r"\midrule",
    ]
    previous_system = ""
    for row in rows:
        if previous_system == "Duffing" and row.system == "Van der Pol":
            lines.append(r"\midrule")
        lines.append(
            f"{row.system} & {row.rollout_mode_label} & "
            f"{_format_sci(row.e1.mean, digits=3)} & "
            f"{_format_sci(row.e20.mean, digits=3)} & "
            f"{_format_sci(row.e200.mean, digits=3)} \\\\" 
        )
        previous_system = row.system
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_metadata(path: Path, args: CliArgs, *, duffing_summary: Path, vanderpol_summary: Path) -> None:
    metadata = {
        "table": "Table 5",
        "description": "Projection diagnostics for Duffing and Van der Pol.",
        "source_scripts": [
            "experiment_04_duffing_projection_diagnostics.py",
            "experiment_08_vanderpol_projection_diagnostics.py",
        ],
        "manuscript_convention": {
            "duffing": "Use experiment_04 defaults: C=15, omega=12.",
            "vanderpol": "Use diagnostic default C=20, omega=4, overriding older experiment_08 local defaults.",
            "reported_cells": "Mean relative association error over three runs at h=1,20,200.",
            "included_rollout_modes": list(DISPLAY_MODE_ORDER),
        },
        "input_summaries": {
            "duffing": str(duffing_summary),
            "vanderpol": str(vanderpol_summary),
        },
        "args": {
            key: str(value) if isinstance(value, Path) else value
            for key, value in asdict(args).items()
        },
    }
    path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")


def _print_rows(rows: Iterable[TableRow]) -> None:
    print("\nTable 5 values:")
    for row in rows:
        print(
            f"  {row.system:11s} | {row.rollout_mode_key:32s} | "
            f"E1={_format_sci(row.e1.mean, digits=3):>18s} | "
            f"E20={_format_sci(row.e20.mean, digits=3):>18s} | "
            f"E200={_format_sci(row.e200.mean, digits=3):>18s}"
        )


def main() -> None:
    args = _parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    duffing_summary, vanderpol_summary = _resolve_summaries(args)
    duffing_rows = _read_summary(duffing_summary)
    vanderpol_rows = _read_summary(vanderpol_summary)

    table_rows = _build_system_rows("Duffing", duffing_rows, source_path=duffing_summary)
    table_rows.extend(_build_system_rows("Van der Pol", vanderpol_rows, source_path=vanderpol_summary))

    csv_path = args.output_dir / "table5_projection_values.csv"
    md_path = args.output_dir / "table5_projection_values.md"
    tex_path = args.output_dir / "table5_projection_values.tex"
    metadata_path = args.output_dir / "table5_projection_metadata.json"

    _write_csv(csv_path, table_rows)
    _write_markdown(md_path, table_rows)
    _write_latex(tex_path, table_rows)
    _write_metadata(metadata_path, args, duffing_summary=duffing_summary, vanderpol_summary=vanderpol_summary)

    _print_rows(table_rows)
    print("\nWrote:")
    print(f"  {csv_path}")
    print(f"  {md_path}")
    print(f"  {tex_path}")
    print(f"  {metadata_path}")


if __name__ == "__main__":
    main()
